Pre conference content update
EuroPython/website pull request #156
Opened 2022-07-07 20:37 UTC by hypha

2022-07-07 20:42 UTC, hypha commented
Missing: 
1. Our 2022 teams
2. Acknowledgement @artcz

2022-07-07 20:45 UTC, hypha commented
I spelled COVID wrong, hopefully only in the commit message.

2022-07-07 22:22 UTC, Vaibhavs10 requested changes

2022-07-07 22:22 UTC, Vaibhavs10 commented on data/pages-content/faq.md
> +A. As of 7 March 2022 social distancing is not required. We will have stickers indicating people's comfort level for interaction: Happy to hug; Happy to handshake; Elbow bumps only; I like my distanc
If we can then let's emphasis on stickers.

2022-07-08 12:33 UTC, patrick91 commented
@hypha maybe we can add a page under info & support?

2022-07-09 21:55 UTC, hypha commented on data/pages-content/covid-info.md
> +- The CCD staff will wear face-masks;
No, because we decided not to enforce volunteers and will just strongly encourage.

2022-07-10 14:51 UTC, merged