PyLadies social event page
EuroPython/website pull request #312
Opened 2023-05-27 10:26 UTC by clytaemnestra

2023-05-27 14:55 UTC, befeleme requested changes
I like it! Some suggestions were proposed inline.
The date on the social card banner is wrong: it should be 21 July 2023.

What do you think about adding a form to gauge the interest from the community? I can prepare one and add the button - similarly to the way Snake workshop was done

2023-05-27 14:55 UTC, befeleme commented on data/pages-content/pyladies-social-event.md
> +- **When**: 28 July 2023
```suggestion
- **When**: 21 July 2023, start: 7 PM
```

2023-05-27 14:55 UTC, befeleme commented on data/pages-content/pyladies-social-event.md
> +- **Where**: pub Hospůdka na Hradbách, 10 minutes by foot from Prague Congress Center
```suggestion
- **Where**: pub Hospůdka na Hradbách, 10 minutes on foot from Prague Congress Centre
```

2023-05-27 14:55 UTC, befeleme commented on data/pages-content/pyladies-social-event.md
> +   This year we're hosting a social event for PyLadies from Czech Republic and abroad. Let's connect, share and celebrate!
```suggestion
   This year we're hosting a social event for PyLadies from the Czech Republic and abroad. Let's connect, share and celebrate!
```

2023-05-27 17:33 UTC, clytaemnestra commented
> I like it! Some suggestions were proposed inline. The date on the social card banner is wrong: it should be 21 July 2023.
> 
> What do you think about adding a form to gauge the interest from the community? I can prepare one and add the button - similarly to the way Snake workshop was done

I remember we were discussing it, but I don't remember what was the conclusion. We definitely want to have it open for everyone even if they haven't registered. 

@hypha do you remember?

2023-05-27 17:37 UTC, hypha commented
> > I like it! Some suggestions were proposed inline. The date on the social card banner is wrong: it should be 21 July 2023.
> > What do you think about adding a form to gauge the interest from the community? I can prepare one and add the button - similarly to the way Snake workshop was done
> 
> I remember we were discussing it, but I don't remember what was the conclusion. We definitely want to have it open for everyone even if they haven't registered.
> 
> @hypha do you remember?

Hey! I think we said that we could have a form to gauge interest but make it clear (on the form and website ) that this is mainly to help us with planning and doesn't mean they cannot join without signing up.

2023-05-27 17:56 UTC, clytaemnestra commented
Okay, let's do it like that 🙂 So @befeleme let me know once the form is ready and I can update the page.

2023-05-31 11:41 UTC, befeleme commented on data/pages-content/pyladies-social-event.md
> +
```suggestion

<div style={{textAlign: "center", marginBottom: 20}}>
<ButtonLink href="https://forms.gle/Uz8Xamou6ik4mLEp6"> Register your interest now! </ButtonLink>
</div>

```

2023-06-02 08:12 UTC, befeleme commented
@hypha, could you please rerun the deployment for visual control of the rendering? Thank you!

2023-06-02 08:15 UTC, hypha commented
> @hypha, could you please rerun the deployment for visual control of the rendering? Thank you!
Of course! Sorry for the delay, @befeleme

2023-06-02 08:17 UTC, befeleme approved these changes
LGTM!

2023-06-02 10:49 UTC, hypha approved these changes
LGTM! Let me know when you want me to merge! <3

2023-06-02 15:37 UTC, merged