Proposed sprint for Lance/LanceDB
EuroPython/website pull request #356
Opened 2023-07-07 22:59 UTC by changhiskhan

Lance is a new columnar format for multi-modal AI and billion scale vector search. It's 2000x faster than parquet for random access, comes with a scalable vector index, and is used as the storage layer for petabyte scale unstructured data lakes

2023-07-08 11:58 UTC, rodrigogiraoserrao requested changes
Thanks for contributing!

Just a couple of requests before merging.

2023-07-08 11:58 UTC, rodrigogiraoserrao commented on data/pages-content/sprints.md
> +- Room: RB 105
Please update the occupancy in the room list above.

2023-07-08 11:58 UTC, rodrigogiraoserrao commented on data/pages-content/sprints.md
> +### Lance - columnar format for multi-modal AI and billion-scale vector search
This is a _long_ heading!
The heading should be the name of the project. 😊

```suggestion
### Lance - modern columnar data format
```
```suggestion
### Lance - columnar data format for ML
```
```suggestion
### Lance - faster parquet alternative
```

2023-07-12 23:16 UTC, changhiskhan commented
> Thanks for contributing!
> 
> Just a couple of requests before merging.

Thanks for the review comments! PR updated.

2023-07-13 13:19 UTC, rodrigogiraoserrao approved these changes

2023-07-13 13:47 UTC, merged

2023-07-13 13:47 UTC, rodrigogiraoserrao commented
Thanks for the sprint contribution, @changhiskhan.
See you in Prague!